// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySales = `-- name: GetDailySales :one
SELECT
    COALESCE(SUM(mi.price * oi.quantity), 0) AS total_sales
FROM orders o
JOIN order_items oi ON o.id = oi.order_id
JOIN menu_items mi ON oi.menu_item_id = mi.id
JOIN table_sessions ts ON o.table_session_id = ts.id
JOIN tables t ON ts.table_id = t.id
WHERE o.status = 'paid'
AND o.created_at >= CURRENT_DATE
AND o.created_at <  CURRENT_DATE + INTERVAL '1 day'
AND t.branch_id = $1
`

// Fix: range comparison instead of DATE() so the index on created_at is used
func (q *Queries) GetDailySales(ctx context.Context, branchID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDailySales, branchID)
	var total_sales interface{}
	err := row.Scan(&total_sales)
	return total_sales, err
}

const getPeakHours = `-- name: GetPeakHours :many
SELECT
    EXTRACT(HOUR FROM o.created_at) AS hour,
    COUNT(*) AS order_count
FROM orders o
JOIN table_sessions ts ON o.table_session_id = ts.id
JOIN tables t ON ts.table_id = t.id
WHERE t.branch_id = $1
AND o.status IN ('paid', 'served')      -- exclude pending/cancelled
GROUP BY hour
ORDER BY order_count DESC
`

type GetPeakHoursRow struct {
	Hour       pgtype.Numeric
	OrderCount int64
}

// Fix: filter to meaningful statuses only
func (q *Queries) GetPeakHours(ctx context.Context, branchID uuid.UUID) ([]GetPeakHoursRow, error) {
	rows, err := q.db.Query(ctx, getPeakHours, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPeakHoursRow
	for rows.Next() {
		var i GetPeakHoursRow
		if err := rows.Scan(&i.Hour, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularItems = `-- name: GetPopularItems :many
SELECT
    mi.name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN orders o ON oi.order_id = o.id
JOIN menu_items mi ON oi.menu_item_id = mi.id
JOIN table_sessions ts ON o.table_session_id = ts.id
JOIN tables t ON ts.table_id = t.id
WHERE t.branch_id = $1
AND o.status IN ('paid', 'served')      -- exclude pending/cancelled
GROUP BY mi.name
ORDER BY total_sold DESC
LIMIT 5
`

type GetPopularItemsRow struct {
	Name      string
	TotalSold int64
}

// Fix: filter to meaningful statuses only
func (q *Queries) GetPopularItems(ctx context.Context, branchID uuid.UUID) ([]GetPopularItemsRow, error) {
	rows, err := q.db.Query(ctx, getPopularItems, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularItemsRow
	for rows.Next() {
		var i GetPopularItemsRow
		if err := rows.Scan(&i.Name, &i.TotalSold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReturningCustomers = `-- name: GetReturningCustomers :one
SELECT COUNT(*) FROM (
    SELECT o.customer_session_id
    FROM orders o
    JOIN table_sessions ts ON o.table_session_id = ts.id
    JOIN tables t ON ts.table_id = t.id
    WHERE t.branch_id = $1
    AND o.status IN ('paid', 'served')  -- only count real completed visits
    GROUP BY o.customer_session_id
    HAVING COUNT(*) > 1
) AS returning_customers
`

// Fix: filter to meaningful statuses only
func (q *Queries) GetReturningCustomers(ctx context.Context, branchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReturningCustomers, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
