// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrdersBySession = `-- name: GetOrdersBySession :many
SELECT o.id, o.table_session_id, o.customer_session_id, o.cart_id, o.status, o.created_at
FROM orders o
WHERE o.customer_session_id IN (
    SELECT cs.id
    FROM customer_sessions cs
    WHERE cs.table_session_id = $1
)
`

func (q *Queries) GetOrdersBySession(ctx context.Context, tableSessionID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersBySession, tableSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TableSessionID,
			&i.CustomerSessionID,
			&i.CartID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrdersPaid = `-- name: MarkOrdersPaid :exec
UPDATE orders
SET status = 'paid'
WHERE id = ANY($1::uuid[])
`

func (q *Queries) MarkOrdersPaid(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOrdersPaid, dollar_1)
	return err
}
