// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
 id,
 tenant_id,
 name,
 location
)
VALUES ($1,$2,$3,$4)
RETURNING id, tenant_id, name, location, created_at
`

type CreateBranchParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Location string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Location,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}
