// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (
 id,
 tenant_id,
 name,
 location
)
VALUES ($1,$2,$3,$4)
RETURNING id, tenant_id, name, location, created_at
`

type CreateBranchParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Location string
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Location,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, tenant_id, name, location, created_at
FROM branches
WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchesByTenant = `-- name: GetBranchesByTenant :many
SELECT id, tenant_id, name, location, created_at
FROM branches
WHERE tenant_id = $1
`

func (q *Queries) GetBranchesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, getBranchesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Location,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
