// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (
    id,
    cart_id,
    menu_item_id,
    quantity,
    added_by
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, cart_id, menu_item_id, quantity, added_by, created_at
`

type AddCartItemParams struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
	AddedBy    uuid.UUID
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem,
		arg.ID,
		arg.CartID,
		arg.MenuItemID,
		arg.Quantity,
		arg.AddedBy,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MenuItemID,
		&i.Quantity,
		&i.AddedBy,
		&i.CreatedAt,
	)
	return i, err
}

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCartItems(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCartItems, cartID)
	return err
}

const getCartItems = `-- name: GetCartItems :many
SELECT id, cart_id, menu_item_id, quantity, added_by, created_at
FROM cart_items
WHERE cart_id = $1
`

func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.MenuItemID,
			&i.Quantity,
			&i.AddedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
