// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomerSession = `-- name: CreateCustomerSession :one
INSERT INTO customer_sessions (
    id,
    table_session_id,
    name
)
VALUES ($1, $2, $3)
RETURNING id, table_session_id, name, created_at
`

type CreateCustomerSessionParams struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	Name           string
}

func (q *Queries) CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) (CustomerSession, error) {
	row := q.db.QueryRow(ctx, createCustomerSession, arg.ID, arg.TableSessionID, arg.Name)
	var i CustomerSession
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerSession = `-- name: GetCustomerSession :one
SELECT id, table_session_id, name, created_at
FROM customer_sessions
WHERE id = $1
`

func (q *Queries) GetCustomerSession(ctx context.Context, id uuid.UUID) (CustomerSession, error) {
	row := q.db.QueryRow(ctx, getCustomerSession, id)
	var i CustomerSession
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomersByTableSession = `-- name: ListCustomersByTableSession :many
SELECT id, table_session_id, name, created_at
FROM customer_sessions
WHERE table_session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCustomersByTableSession(ctx context.Context, tableSessionID uuid.UUID) ([]CustomerSession, error) {
	rows, err := q.db.Query(ctx, listCustomersByTableSession, tableSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerSession
	for rows.Next() {
		var i CustomerSession
		if err := rows.Scan(
			&i.ID,
			&i.TableSessionID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
