// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (
    id,
    branch_id,
    name,
    stock,
    threshold
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, branch_id, name, stock, threshold, created_at
`

type CreateInventoryItemParams struct {
	ID        uuid.UUID
	BranchID  uuid.UUID
	Name      string
	Stock     int32
	Threshold int32
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.ID,
		arg.BranchID,
		arg.Name,
		arg.Stock,
		arg.Threshold,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Stock,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory_items WHERE id = $1 AND branch_id = $2
`

type DeleteInventoryItemParams struct {
	ID       uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) DeleteInventoryItem(ctx context.Context, arg DeleteInventoryItemParams) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, arg.ID, arg.BranchID)
	return err
}

const getInventoryItemByID = `-- name: GetInventoryItemByID :one
SELECT id, branch_id, name, stock, threshold, created_at
FROM inventory_items
WHERE id = $1
  AND branch_id = $2
`

type GetInventoryItemByIDParams struct {
	ID       uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) GetInventoryItemByID(ctx context.Context, arg GetInventoryItemByIDParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItemByID, arg.ID, arg.BranchID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Stock,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryItemsByBranch = `-- name: GetInventoryItemsByBranch :many
SELECT id, branch_id, name, stock, threshold, created_at
FROM inventory_items
WHERE branch_id = $1
ORDER BY name ASC
`

func (q *Queries) GetInventoryItemsByBranch(ctx context.Context, branchID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, getInventoryItemsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Stock,
			&i.Threshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLowStockItems = `-- name: GetLowStockItems :many
SELECT id, branch_id, name, stock, threshold, created_at
FROM inventory_items
WHERE branch_id = $1
  AND stock <= threshold
`

func (q *Queries) GetLowStockItems(ctx context.Context, branchID uuid.UUID) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, getLowStockItems, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Stock,
			&i.Threshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStock = `-- name: SetStock :one
UPDATE inventory_items
SET stock = $2
WHERE id = $1
  AND branch_id = $3
RETURNING id, branch_id, name, stock, threshold, created_at
`

type SetStockParams struct {
	ID       uuid.UUID
	Stock    int32
	BranchID uuid.UUID
}

func (q *Queries) SetStock(ctx context.Context, arg SetStockParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, setStock, arg.ID, arg.Stock, arg.BranchID)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Stock,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const updateStock = `-- name: UpdateStock :exec
UPDATE inventory_items
SET stock = stock - $2
WHERE id = $1
  AND branch_id = $3
`

type UpdateStockParams struct {
	ID       uuid.UUID
	Stock    int32
	BranchID uuid.UUID
}

func (q *Queries) UpdateStock(ctx context.Context, arg UpdateStockParams) error {
	_, err := q.db.Exec(ctx, updateStock, arg.ID, arg.Stock, arg.BranchID)
	return err
}
