// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu_categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMenuCategory = `-- name: CreateMenuCategory :one
INSERT INTO menu_categories (
    id,
    menu_id,
    name,
    display_order
)
VALUES ($1,$2,$3,$4)
RETURNING id, menu_id, name, display_order, created_at
`

type CreateMenuCategoryParams struct {
	ID           uuid.UUID
	MenuID       uuid.UUID
	Name         string
	DisplayOrder int32
}

func (q *Queries) CreateMenuCategory(ctx context.Context, arg CreateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, createMenuCategory,
		arg.ID,
		arg.MenuID,
		arg.Name,
		arg.DisplayOrder,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Name,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getMenuCategories = `-- name: GetMenuCategories :many
SELECT id, menu_id, name, display_order, created_at
FROM menu_categories
WHERE menu_id = $1
ORDER BY display_order
`

func (q *Queries) GetMenuCategories(ctx context.Context, menuID uuid.UUID) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, getMenuCategories, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.Name,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
