// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_view.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFullMenu = `-- name: GetFullMenu :many
SELECT
    mc.id as category_id,
    mc.name as category_name,
    mc.display_order,
    COALESCE(
        json_agg(
            json_build_object(
                'id', mi.id,
                'name', mi.name,
                'description', mi.description,
                'price', mi.price,
                'available', mi.available,
                'sold_out', mi.sold_out,
                'is_special', mi.is_special
            ) ORDER BY mi.name
        ) FILTER (WHERE mi.id IS NOT NULL),
        '[]'::json
    )::json AS items
FROM menu_categories mc
LEFT JOIN menu_items mi ON mc.id = mi.category_id
    AND mi.available = TRUE
    AND mi.sold_out = FALSE
WHERE mc.menu_id = $1
GROUP BY mc.id, mc.name, mc.display_order
ORDER BY mc.display_order
`

type GetFullMenuRow struct {
	CategoryID   uuid.UUID
	CategoryName string
	DisplayOrder int32
	Items        []byte
}

func (q *Queries) GetFullMenu(ctx context.Context, menuID uuid.UUID) ([]GetFullMenuRow, error) {
	rows, err := q.db.Query(ctx, getFullMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullMenuRow
	for rows.Next() {
		var i GetFullMenuRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.DisplayOrder,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
