// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (
    id,
    category_id,
    name,
    description,
    price
)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, category_id, name, description, price, available, sold_out, is_special, created_at
`

type CreateMenuItemParams struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description string
	Price       float64
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Available,
		&i.SoldOut,
		&i.IsSpecial,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1
`

func (q *Queries) DeleteMenuItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, id)
	return err
}

const getCategoryItems = `-- name: GetCategoryItems :many
SELECT id, category_id, name, description, price, available, sold_out, is_special, created_at
FROM menu_items
WHERE category_id = $1
AND available = TRUE
AND sold_out = FALSE
`

func (q *Queries) GetCategoryItems(ctx context.Context, categoryID uuid.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getCategoryItems, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Available,
			&i.SoldOut,
			&i.IsSpecial,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDailySpecial = `-- name: SetDailySpecial :exec
UPDATE menu_items
SET is_special = $2
WHERE id = $1
`

type SetDailySpecialParams struct {
	ID        uuid.UUID
	IsSpecial bool
}

func (q *Queries) SetDailySpecial(ctx context.Context, arg SetDailySpecialParams) error {
	_, err := q.db.Exec(ctx, setDailySpecial, arg.ID, arg.IsSpecial)
	return err
}

const setMenuItemAvailable = `-- name: SetMenuItemAvailable :exec
UPDATE menu_items 
SET sold_out = false, available = true 
WHERE id = $1
`

func (q *Queries) SetMenuItemAvailable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setMenuItemAvailable, id)
	return err
}

const setMenuItemSoldOut = `-- name: SetMenuItemSoldOut :exec
UPDATE menu_items
SET 
    sold_out = $2,
    available = CASE 
        WHEN $2 = true THEN false
        ELSE available
    END
WHERE id = $1
`

type SetMenuItemSoldOutParams struct {
	ID      uuid.UUID
	SoldOut bool
}

func (q *Queries) SetMenuItemSoldOut(ctx context.Context, arg SetMenuItemSoldOutParams) error {
	_, err := q.db.Exec(ctx, setMenuItemSoldOut, arg.ID, arg.SoldOut)
	return err
}

const updateMenuItemPrice = `-- name: UpdateMenuItemPrice :exec
UPDATE menu_items
SET price = $2
WHERE id = $1
`

type UpdateMenuItemPriceParams struct {
	ID    uuid.UUID
	Price float64
}

func (q *Queries) UpdateMenuItemPrice(ctx context.Context, arg UpdateMenuItemPriceParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemPrice, arg.ID, arg.Price)
	return err
}
