// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (
    id,
    branch_id
)
VALUES ($1,$2)
RETURNING id, branch_id, created_at
`

type CreateMenuParams struct {
	ID       uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu, arg.ID, arg.BranchID)
	var i Menu
	err := row.Scan(&i.ID, &i.BranchID, &i.CreatedAt)
	return i, err
}

const getBranchMenus = `-- name: GetBranchMenus :many
SELECT id, branch_id, created_at
FROM menus
WHERE branch_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetBranchMenus(ctx context.Context, branchID uuid.UUID) ([]Menu, error) {
	rows, err := q.db.Query(ctx, getBranchMenus, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(&i.ID, &i.BranchID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenu = `-- name: GetMenu :one
SELECT id, branch_id, created_at
FROM menus
WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id uuid.UUID) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i Menu
	err := row.Scan(&i.ID, &i.BranchID, &i.CreatedAt)
	return i, err
}
