// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Branch struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Location  string
	CreatedAt time.Time
}

type CartItem struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
	AddedBy    uuid.UUID
	CreatedAt  time.Time
}

type CartParticipant struct {
	ID                uuid.UUID
	CartID            uuid.UUID
	CustomerSessionID uuid.UUID
	JoinedAt          time.Time
}

type CustomerSession struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	Name           string
	CreatedAt      time.Time
}

type InventoryItem struct {
	ID        uuid.UUID
	BranchID  uuid.UUID
	Name      string
	Stock     int32
	Threshold int32
	CreatedAt time.Time
}

type Menu struct {
	ID        uuid.UUID
	BranchID  uuid.UUID
	CreatedAt time.Time
}

type MenuCategory struct {
	ID           uuid.UUID
	MenuID       uuid.UUID
	Name         string
	DisplayOrder int32
	CreatedAt    time.Time
}

type MenuItem struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description string
	Price       float64
	Available   bool
	SoldOut     bool
	IsSpecial   bool
	CreatedAt   time.Time
}

type MenuItemIngredient struct {
	ID               uuid.UUID
	MenuItemID       uuid.UUID
	InventoryItemID  pgtype.UUID
	QuantityRequired int32
}

type Order struct {
	ID                uuid.UUID
	TableSessionID    uuid.UUID
	CustomerSessionID uuid.UUID
	CartID            uuid.UUID
	Status            string
	CreatedAt         time.Time
}

type OrderItem struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
}

type Payment struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BranchID       uuid.UUID
	TableSessionID uuid.UUID
	Method         string
	Status         string
	Amount         float64
	MpesaReceipt   pgtype.Text
	InitiatedBy    pgtype.UUID
	ConfirmedBy    pgtype.UUID
	CreatedAt      time.Time
	ConfirmedAt    pgtype.Timestamp
}

type Plan struct {
	ID                uuid.UUID
	Name              string
	DisplayName       string
	PriceKes          float64
	BillingPeriodDays int32
	MaxBranches       int32
	IsActive          bool
	CreatedAt         time.Time
}

type PlatformAdmin struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type SharedCart struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	CreatedBy      uuid.UUID
	Status         string
	CreatedAt      time.Time
}

type StaffActivity struct {
	ID         uuid.UUID
	StaffID    uuid.UUID
	BranchID   uuid.UUID
	Action     string
	EntityType string
	EntityID   uuid.UUID
	OldData    json.RawMessage
	NewData    json.RawMessage
	IpAddress  netip.Addr
	Note       string
	CreatedAt  time.Time
}

type StaffUser struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	BranchID     pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedBy    pgtype.UUID
	CreatedAt    time.Time
}

type SubscriptionPayment struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	PlanID            uuid.UUID
	Amount            float64
	Currency          string
	PaystackReference string
	Status            string
	InitiatedBy       pgtype.UUID
	CreatedAt         time.Time
	VerifiedAt        pgtype.Timestamp
}

type Table struct {
	ID          uuid.UUID
	BranchID    uuid.UUID
	TableNumber int32
}

type TableSession struct {
	ID        uuid.UUID
	TableID   uuid.UUID
	Status    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Tenant struct {
	ID                    uuid.UUID
	Name                  string
	Plan                  string
	CreatedAt             time.Time
	SubscriptionStatus    string
	SubscriptionExpiresAt time.Time
}
