// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Branch struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Location  string
	CreatedAt time.Time
}

type CartItem struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
	AddedBy    uuid.UUID
	CreatedAt  time.Time
}

type CartParticipant struct {
	ID                uuid.UUID
	CartID            uuid.UUID
	CustomerSessionID uuid.UUID
	JoinedAt          time.Time
}

type CustomerSession struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	Name           string
	CreatedAt      time.Time
}

type Menu struct {
	ID        uuid.UUID
	BranchID  uuid.UUID
	CreatedAt time.Time
}

type MenuCategory struct {
	ID           uuid.UUID
	MenuID       uuid.UUID
	Name         string
	DisplayOrder int32
	CreatedAt    time.Time
}

type MenuItem struct {
	ID          uuid.UUID
	CategoryID  uuid.UUID
	Name        string
	Description string
	Price       float64
	Available   bool
	SoldOut     bool
	IsSpecial   bool
	CreatedAt   time.Time
}

type Order struct {
	ID                uuid.UUID
	TableSessionID    uuid.UUID
	CustomerSessionID uuid.UUID
	CartID            uuid.UUID
	Status            string
	CreatedAt         time.Time
}

type OrderItem struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
}

type SharedCart struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	CreatedBy      uuid.UUID
	Status         string
	CreatedAt      time.Time
}

type StaffUser struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	BranchID     uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedBy    uuid.UUID
	CreatedAt    time.Time
}

type Table struct {
	ID          uuid.UUID
	BranchID    uuid.UUID
	TableNumber int32
}

type TableSession struct {
	ID        uuid.UUID
	TableID   uuid.UUID
	Status    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Plan      string
	CreatedAt time.Time
}
