// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeOrderBill = `-- name: CloseOrderBill :one
UPDATE orders
SET status = 'closed'
WHERE id = $1
RETURNING id, table_session_id, customer_session_id, cart_id, status, created_at
`

func (q *Queries) CloseOrderBill(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, closeOrderBill, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CustomerSessionID,
		&i.CartID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    table_session_id,
    customer_session_id,
    cart_id,
    status
)
VALUES ($1,$2,$3,$4,'pending')
RETURNING id, table_session_id, customer_session_id, cart_id, status, created_at
`

type CreateOrderParams struct {
	ID                uuid.UUID
	TableSessionID    uuid.UUID
	CustomerSessionID uuid.UUID
	CartID            uuid.UUID
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.TableSessionID,
		arg.CustomerSessionID,
		arg.CartID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CustomerSessionID,
		&i.CartID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    menu_item_id,
    quantity
)
VALUES ($1,$2,$3,$4)
RETURNING id, order_id, menu_item_id, quantity
`

type CreateOrderItemParams struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	MenuItemID uuid.UUID
	Quantity   int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, table_session_id, customer_session_id, cart_id, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CustomerSessionID,
		&i.CartID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItemsByOrder = `-- name: GetOrderItemsByOrder :many
SELECT 
    oi.id,
    oi.order_id,
    oi.quantity,
    mi.name,
    mi.price
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
WHERE oi.order_id = $1
`

type GetOrderItemsByOrderRow struct {
	ID       uuid.UUID
	OrderID  uuid.UUID
	Quantity int32
	Name     string
	Price    float64
}

func (q *Queries) GetOrderItemsByOrder(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsByOrderRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderRow
	for rows.Next() {
		var i GetOrderItemsByOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Quantity,
			&i.Name,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByTableSession = `-- name: GetOrdersByTableSession :many
SELECT id, table_session_id, customer_session_id, cart_id, status, created_at
FROM orders
WHERE table_session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByTableSession(ctx context.Context, tableSessionID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByTableSession, tableSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TableSessionID,
			&i.CustomerSessionID,
			&i.CartID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentOrdersByBranch = `-- name: GetRecentOrdersByBranch :many
SELECT 
    o.id,
    o.table_session_id,
    o.customer_session_id,
    o.cart_id,
    o.status,
    o.created_at,
    t.table_number
FROM orders o
JOIN table_sessions ts ON ts.id = o.table_session_id
JOIN tables t ON t.id = ts.table_id
WHERE t.branch_id = $1
ORDER BY o.created_at DESC
LIMIT 50
`

type GetRecentOrdersByBranchRow struct {
	ID                uuid.UUID
	TableSessionID    uuid.UUID
	CustomerSessionID uuid.UUID
	CartID            uuid.UUID
	Status            string
	CreatedAt         time.Time
	TableNumber       int32
}

func (q *Queries) GetRecentOrdersByBranch(ctx context.Context, branchID uuid.UUID) ([]GetRecentOrdersByBranchRow, error) {
	rows, err := q.db.Query(ctx, getRecentOrdersByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentOrdersByBranchRow
	for rows.Next() {
		var i GetRecentOrdersByBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.TableSessionID,
			&i.CustomerSessionID,
			&i.CartID,
			&i.Status,
			&i.CreatedAt,
			&i.TableNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusSafe = `-- name: UpdateOrderStatusSafe :one
UPDATE orders
SET status = $3
WHERE id = $1
AND status = $2
RETURNING id, table_session_id, customer_session_id, cart_id, status, created_at
`

type UpdateOrderStatusSafeParams struct {
	ID       uuid.UUID
	Status   string
	Status_2 string
}

// SAFE + IDEMPOTENT STATUS UPDATE
func (q *Queries) UpdateOrderStatusSafe(ctx context.Context, arg UpdateOrderStatusSafeParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatusSafe, arg.ID, arg.Status, arg.Status_2)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CustomerSessionID,
		&i.CartID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
