// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_inventory.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const autoMarkSoldOut = `-- name: AutoMarkSoldOut :exec
UPDATE menu_items
SET sold_out = TRUE
WHERE id IN (
    SELECT DISTINCT mii.menu_item_id
    FROM menu_item_ingredients mii
    JOIN inventory_items inv ON inv.id = mii.inventory_item_id
    WHERE inv.stock <= 0
      AND inv.branch_id = $1
)
`

func (q *Queries) AutoMarkSoldOut(ctx context.Context, branchID uuid.UUID) error {
	_, err := q.db.Exec(ctx, autoMarkSoldOut, branchID)
	return err
}

const deductStockForOrder = `-- name: DeductStockForOrder :exec
UPDATE inventory_items inv
SET stock = inv.stock - (mii.quantity_required * oi.quantity)
FROM order_items oi
JOIN menu_item_ingredients mii ON mii.menu_item_id = oi.menu_item_id
WHERE inv.id = mii.inventory_item_id
  AND oi.order_id = $1
  AND inv.branch_id = $2
`

type DeductStockForOrderParams struct {
	OrderID  uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) DeductStockForOrder(ctx context.Context, arg DeductStockForOrderParams) error {
	_, err := q.db.Exec(ctx, deductStockForOrder, arg.OrderID, arg.BranchID)
	return err
}

const restoreStockForOrder = `-- name: RestoreStockForOrder :exec
UPDATE inventory_items inv
SET stock = inv.stock + (mii.quantity_required * oi.quantity)
FROM order_items oi
JOIN menu_item_ingredients mii ON mii.menu_item_id = oi.menu_item_id
WHERE inv.id = mii.inventory_item_id
  AND oi.order_id = $1
  AND inv.branch_id = $2
`

type RestoreStockForOrderParams struct {
	OrderID  uuid.UUID
	BranchID uuid.UUID
}

func (q *Queries) RestoreStockForOrder(ctx context.Context, arg RestoreStockForOrderParams) error {
	_, err := q.db.Exec(ctx, restoreStockForOrder, arg.OrderID, arg.BranchID)
	return err
}
