// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET status = 'cancelled'
WHERE id = $1 AND status = 'pending'
RETURNING id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at
`

func (q *Queries) CancelPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, cancelPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.TableSessionID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.MpesaReceipt,
		&i.InitiatedBy,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET status = 'confirmed',
    confirmed_by = $2,
    confirmed_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at
`

type ConfirmPaymentParams struct {
	ID          uuid.UUID
	ConfirmedBy pgtype.UUID
}

func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, arg.ID, arg.ConfirmedBy)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.TableSessionID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.MpesaReceipt,
		&i.InitiatedBy,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id, tenant_id, branch_id, table_session_id,
    method, amount, initiated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at
`

type CreatePaymentParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	BranchID       uuid.UUID
	TableSessionID uuid.UUID
	Method         string
	Amount         float64
	InitiatedBy    pgtype.UUID
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.TableSessionID,
		arg.Method,
		arg.Amount,
		arg.InitiatedBy,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.TableSessionID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.MpesaReceipt,
		&i.InitiatedBy,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.TableSessionID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.MpesaReceipt,
		&i.InitiatedBy,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getPaymentsByTableSession = `-- name: GetPaymentsByTableSession :many
SELECT id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at FROM payments
WHERE table_session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPaymentsByTableSession(ctx context.Context, tableSessionID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPaymentsByTableSession, tableSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.TableSessionID,
			&i.Method,
			&i.Status,
			&i.Amount,
			&i.MpesaReceipt,
			&i.InitiatedBy,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPaymentByTableSession = `-- name: GetPendingPaymentByTableSession :one
SELECT id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at FROM payments
WHERE table_session_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingPaymentByTableSession(ctx context.Context, tableSessionID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentByTableSession, tableSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.TableSessionID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.MpesaReceipt,
		&i.InitiatedBy,
		&i.ConfirmedBy,
		&i.CreatedAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getPendingPaymentsByBranch = `-- name: GetPendingPaymentsByBranch :many
SELECT id, tenant_id, branch_id, table_session_id, method, status, amount, mpesa_receipt, initiated_by, confirmed_by, created_at, confirmed_at FROM payments
WHERE branch_id = $1 AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) GetPendingPaymentsByBranch(ctx context.Context, branchID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, getPendingPaymentsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.TableSessionID,
			&i.Method,
			&i.Status,
			&i.Amount,
			&i.MpesaReceipt,
			&i.InitiatedBy,
			&i.ConfirmedBy,
			&i.CreatedAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableSessionOutstandingTotal = `-- name: GetTableSessionOutstandingTotal :one
SELECT COALESCE(SUM(oi.quantity * mi.price), 0)::float8 AS total
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN menu_items mi ON mi.id = oi.menu_item_id
WHERE o.table_session_id = $1
  AND o.status = 'served'
`

// Server-side source of truth for what's owed on a bill. Never trust a
// client-supplied amount for payment initiation — always recompute here.
func (q *Queries) GetTableSessionOutstandingTotal(ctx context.Context, tableSessionID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTableSessionOutstandingTotal, tableSessionID)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const getTableSessionOwnership = `-- name: GetTableSessionOwnership :one
SELECT b.tenant_id, t.branch_id
FROM table_sessions ts
JOIN tables t ON t.id = ts.table_id
JOIN branches b ON b.id = t.branch_id
WHERE ts.id = $1
`

type GetTableSessionOwnershipRow struct {
	TenantID uuid.UUID
	BranchID uuid.UUID
}

// Derives the true tenant_id/branch_id for a table session by walking
// table_session -> table -> branch. Used so payments.tenant_id/branch_id
// are always computed from the table session itself rather than trusted
// from caller-supplied values, which could otherwise drift out of sync
// (e.g. a staff member's own JWT tenant/branch not matching the table
// session they're being asked to act on).
func (q *Queries) GetTableSessionOwnership(ctx context.Context, id uuid.UUID) (GetTableSessionOwnershipRow, error) {
	row := q.db.QueryRow(ctx, getTableSessionOwnership, id)
	var i GetTableSessionOwnershipRow
	err := row.Scan(&i.TenantID, &i.BranchID)
	return i, err
}
