// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, display_name, price_kes, billing_period_days, max_branches, is_active, created_at FROM plans
WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.PriceKes,
		&i.BillingPeriodDays,
		&i.MaxBranches,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, display_name, price_kes, billing_period_days, max_branches, is_active, created_at FROM plans
WHERE name = $1 AND is_active = TRUE
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.PriceKes,
		&i.BillingPeriodDays,
		&i.MaxBranches,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, display_name, price_kes, billing_period_days, max_branches, is_active, created_at FROM plans
WHERE is_active = TRUE
ORDER BY price_kes ASC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.PriceKes,
			&i.BillingPeriodDays,
			&i.MaxBranches,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
