// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admins (id, name, email, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password_hash, created_at
`

type CreatePlatformAdminParams struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByEmail = `-- name: GetPlatformAdminByEmail :one
SELECT id, name, email, password_hash, created_at FROM platform_admins
WHERE email = $1
`

func (q *Queries) GetPlatformAdminByEmail(ctx context.Context, email string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByEmail, email)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, name, email, password_hash, created_at FROM platform_admins
WHERE id = $1
`

func (q *Queries) GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
