// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addIngredientToMenuItem = `-- name: AddIngredientToMenuItem :exec
INSERT INTO menu_item_ingredients (
    id,
    menu_item_id,
    inventory_item_id,
    quantity_required
)
VALUES ($1, $2, $3, $4)
`

type AddIngredientToMenuItemParams struct {
	ID               uuid.UUID
	MenuItemID       uuid.UUID
	InventoryItemID  pgtype.UUID
	QuantityRequired int32
}

func (q *Queries) AddIngredientToMenuItem(ctx context.Context, arg AddIngredientToMenuItemParams) error {
	_, err := q.db.Exec(ctx, addIngredientToMenuItem,
		arg.ID,
		arg.MenuItemID,
		arg.InventoryItemID,
		arg.QuantityRequired,
	)
	return err
}

const getIngredientsByMenuItem = `-- name: GetIngredientsByMenuItem :many
SELECT
    mii.id,
    mii.quantity_required,
    inv.id   AS inventory_item_id,
    inv.name AS ingredient_name,
    inv.stock,
    inv.threshold
FROM menu_item_ingredients mii
JOIN inventory_items inv ON inv.id = mii.inventory_item_id
WHERE mii.menu_item_id = $1
`

type GetIngredientsByMenuItemRow struct {
	ID               uuid.UUID
	QuantityRequired int32
	InventoryItemID  uuid.UUID
	IngredientName   string
	Stock            int32
	Threshold        int32
}

func (q *Queries) GetIngredientsByMenuItem(ctx context.Context, menuItemID uuid.UUID) ([]GetIngredientsByMenuItemRow, error) {
	rows, err := q.db.Query(ctx, getIngredientsByMenuItem, menuItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsByMenuItemRow
	for rows.Next() {
		var i GetIngredientsByMenuItemRow
		if err := rows.Scan(
			&i.ID,
			&i.QuantityRequired,
			&i.InventoryItemID,
			&i.IngredientName,
			&i.Stock,
			&i.Threshold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMenuItemsByIngredient = `-- name: GetMenuItemsByIngredient :many
SELECT
    mi.id,
    mi.name,
    mi.available,
    mi.sold_out
FROM menu_item_ingredients mii
JOIN menu_items mi ON mi.id = mii.menu_item_id
WHERE mii.inventory_item_id = $1
`

type GetMenuItemsByIngredientRow struct {
	ID        uuid.UUID
	Name      string
	Available bool
	SoldOut   bool
}

func (q *Queries) GetMenuItemsByIngredient(ctx context.Context, inventoryItemID pgtype.UUID) ([]GetMenuItemsByIngredientRow, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByIngredient, inventoryItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMenuItemsByIngredientRow
	for rows.Next() {
		var i GetMenuItemsByIngredientRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Available,
			&i.SoldOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIngredientFromMenuItem = `-- name: RemoveIngredientFromMenuItem :exec
DELETE FROM menu_item_ingredients
WHERE menu_item_id = $1
  AND inventory_item_id = $2
`

type RemoveIngredientFromMenuItemParams struct {
	MenuItemID      uuid.UUID
	InventoryItemID pgtype.UUID
}

func (q *Queries) RemoveIngredientFromMenuItem(ctx context.Context, arg RemoveIngredientFromMenuItemParams) error {
	_, err := q.db.Exec(ctx, removeIngredientFromMenuItem, arg.MenuItemID, arg.InventoryItemID)
	return err
}

const updateIngredientQuantity = `-- name: UpdateIngredientQuantity :exec
UPDATE menu_item_ingredients
SET quantity_required = $3
WHERE menu_item_id = $1
  AND inventory_item_id = $2
`

type UpdateIngredientQuantityParams struct {
	MenuItemID       uuid.UUID
	InventoryItemID  pgtype.UUID
	QuantityRequired int32
}

func (q *Queries) UpdateIngredientQuantity(ctx context.Context, arg UpdateIngredientQuantityParams) error {
	_, err := q.db.Exec(ctx, updateIngredientQuantity, arg.MenuItemID, arg.InventoryItemID, arg.QuantityRequired)
	return err
}
