// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shared_cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addCartParticipant = `-- name: AddCartParticipant :exec
INSERT INTO cart_participants (
    id,
    cart_id,
    customer_session_id
)
VALUES ($1, $2, $3)
`

type AddCartParticipantParams struct {
	ID                uuid.UUID
	CartID            uuid.UUID
	CustomerSessionID uuid.UUID
}

func (q *Queries) AddCartParticipant(ctx context.Context, arg AddCartParticipantParams) error {
	_, err := q.db.Exec(ctx, addCartParticipant, arg.ID, arg.CartID, arg.CustomerSessionID)
	return err
}

const createSharedCart = `-- name: CreateSharedCart :one
INSERT INTO shared_carts (
    id,
    table_session_id,
    created_by
)
VALUES ($1, $2, $3)
RETURNING id, table_session_id, created_by, status, created_at
`

type CreateSharedCartParams struct {
	ID             uuid.UUID
	TableSessionID uuid.UUID
	CreatedBy      uuid.UUID
}

func (q *Queries) CreateSharedCart(ctx context.Context, arg CreateSharedCartParams) (SharedCart, error) {
	row := q.db.QueryRow(ctx, createSharedCart, arg.ID, arg.TableSessionID, arg.CreatedBy)
	var i SharedCart
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCart = `-- name: GetCart :one
SELECT id, table_session_id, created_by, status, created_at
FROM shared_carts
WHERE id = $1
`

func (q *Queries) GetCart(ctx context.Context, id uuid.UUID) (SharedCart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i SharedCart
	err := row.Scan(
		&i.ID,
		&i.TableSessionID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCartParticipants = `-- name: GetCartParticipants :many
SELECT id, cart_id, customer_session_id, joined_at
FROM cart_participants
WHERE cart_id = $1
`

func (q *Queries) GetCartParticipants(ctx context.Context, cartID uuid.UUID) ([]CartParticipant, error) {
	rows, err := q.db.Query(ctx, getCartParticipants, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartParticipant
	for rows.Next() {
		var i CartParticipant
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.CustomerSessionID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
