// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_activities.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO staff_activities (
    id,
    staff_id,
    branch_id,
    action,
    entity_type,
    entity_id,
    old_data,
    new_data,
    ip_address,
    note
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateActivityParams struct {
	ID         uuid.UUID
	StaffID    uuid.UUID
	BranchID   uuid.UUID
	Action     string
	EntityType string
	EntityID   uuid.UUID
	OldData    json.RawMessage
	NewData    json.RawMessage
	IpAddress  netip.Addr
	Note       string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.ID,
		arg.StaffID,
		arg.BranchID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldData,
		arg.NewData,
		arg.IpAddress,
		arg.Note,
	)
	return err
}
