// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO staff_users (
    id,
    tenant_id,
    branch_id,
    name,
    email,
    password_hash,
    role,
    created_by        
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, tenant_id, branch_id, name, email, password_hash, role, created_by, created_at
`

type CreateStaffUserParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	BranchID     pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	Role         string
	CreatedBy    pgtype.UUID
}

func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error) {
	row := q.db.QueryRow(ctx, createStaffUser,
		arg.ID,
		arg.TenantID,
		arg.BranchID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedBy,
	)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStaffUser = `-- name: DeleteStaffUser :exec
DELETE FROM staff_users WHERE id = $1
`

func (q *Queries) DeleteStaffUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffUser, id)
	return err
}

const getBranchStaff = `-- name: GetBranchStaff :many
SELECT id, tenant_id, branch_id, name, email, password_hash, role, created_by, created_at
FROM staff_users
WHERE branch_id = $1
`

func (q *Queries) GetBranchStaff(ctx context.Context, branchID pgtype.UUID) ([]StaffUser, error) {
	rows, err := q.db.Query(ctx, getBranchStaff, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffUser
	for rows.Next() {
		var i StaffUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BranchID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, tenant_id, branch_id, name, email, password_hash, role, created_by, created_at
FROM staff_users
WHERE email = $1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, email)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, tenant_id, branch_id, name, email, password_hash, role, created_by, created_at
FROM staff_users
WHERE id = $1
`

func (q *Queries) GetStaffByID(ctx context.Context, id uuid.UUID) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BranchID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateStaffPassword = `-- name: UpdateStaffPassword :exec
UPDATE staff_users
SET password_hash = $2
WHERE id = $1
`

type UpdateStaffPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateStaffPassword(ctx context.Context, arg UpdateStaffPasswordParams) error {
	_, err := q.db.Exec(ctx, updateStaffPassword, arg.ID, arg.PasswordHash)
	return err
}
