// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription_payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionPayment = `-- name: CreateSubscriptionPayment :one
INSERT INTO subscription_payments (
    id, tenant_id, plan_id, amount, currency, paystack_reference, initiated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, plan_id, amount, currency, paystack_reference, status, initiated_by, created_at, verified_at
`

type CreateSubscriptionPaymentParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	PlanID            uuid.UUID
	Amount            float64
	Currency          string
	PaystackReference string
	InitiatedBy       pgtype.UUID
}

func (q *Queries) CreateSubscriptionPayment(ctx context.Context, arg CreateSubscriptionPaymentParams) (SubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPayment,
		arg.ID,
		arg.TenantID,
		arg.PlanID,
		arg.Amount,
		arg.Currency,
		arg.PaystackReference,
		arg.InitiatedBy,
	)
	var i SubscriptionPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.PaystackReference,
		&i.Status,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getSubscriptionPaymentByReference = `-- name: GetSubscriptionPaymentByReference :one
SELECT id, tenant_id, plan_id, amount, currency, paystack_reference, status, initiated_by, created_at, verified_at FROM subscription_payments
WHERE paystack_reference = $1
`

func (q *Queries) GetSubscriptionPaymentByReference(ctx context.Context, paystackReference string) (SubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPaymentByReference, paystackReference)
	var i SubscriptionPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.PaystackReference,
		&i.Status,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const listSubscriptionPaymentsByTenant = `-- name: ListSubscriptionPaymentsByTenant :many
SELECT id, tenant_id, plan_id, amount, currency, paystack_reference, status, initiated_by, created_at, verified_at FROM subscription_payments
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionPaymentsByTenant(ctx context.Context, tenantID uuid.UUID) ([]SubscriptionPayment, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPaymentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionPayment
	for rows.Next() {
		var i SubscriptionPayment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlanID,
			&i.Amount,
			&i.Currency,
			&i.PaystackReference,
			&i.Status,
			&i.InitiatedBy,
			&i.CreatedAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionPaymentFailed = `-- name: MarkSubscriptionPaymentFailed :one
UPDATE subscription_payments
SET status = 'failed',
    verified_at = NOW()
WHERE paystack_reference = $1 AND status = 'pending'
RETURNING id, tenant_id, plan_id, amount, currency, paystack_reference, status, initiated_by, created_at, verified_at
`

func (q *Queries) MarkSubscriptionPaymentFailed(ctx context.Context, paystackReference string) (SubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, markSubscriptionPaymentFailed, paystackReference)
	var i SubscriptionPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.PaystackReference,
		&i.Status,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const markSubscriptionPaymentSuccess = `-- name: MarkSubscriptionPaymentSuccess :one
UPDATE subscription_payments
SET status = 'success',
    verified_at = NOW()
WHERE paystack_reference = $1 AND status = 'pending'
RETURNING id, tenant_id, plan_id, amount, currency, paystack_reference, status, initiated_by, created_at, verified_at
`

func (q *Queries) MarkSubscriptionPaymentSuccess(ctx context.Context, paystackReference string) (SubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, markSubscriptionPaymentSuccess, paystackReference)
	var i SubscriptionPayment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Amount,
		&i.Currency,
		&i.PaystackReference,
		&i.Status,
		&i.InitiatedBy,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}
