// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: superadmin_analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlatformOverview = `-- name: GetPlatformOverview :one
SELECT
    (SELECT COUNT(*) FROM tenants)::int                                        AS tenant_count,
    (SELECT COUNT(*) FROM branches)::int                                       AS branch_count,
    (SELECT COUNT(*) FROM staff_users)::int                                    AS staff_count,
    (SELECT COALESCE(SUM(amount), 0) FROM payments WHERE status = 'confirmed')::float8 AS total_platform_revenue
`

type GetPlatformOverviewRow struct {
	TenantCount          int32
	BranchCount          int32
	StaffCount           int32
	TotalPlatformRevenue float64
}

// Top-level summary card. Each figure is an independent scalar subquery,
// so there's no join fan-out risk at all.
func (q *Queries) GetPlatformOverview(ctx context.Context) (GetPlatformOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOverview)
	var i GetPlatformOverviewRow
	err := row.Scan(
		&i.TenantCount,
		&i.BranchCount,
		&i.StaffCount,
		&i.TotalPlatformRevenue,
	)
	return i, err
}

const getTenantByIDForAdmin = `-- name: GetTenantByIDForAdmin :one
SELECT id, name, plan, created_at, subscription_status, subscription_expires_at FROM tenants
WHERE id = $1
`

// Superadmin-scoped tenant lookup (no tenant-isolation check needed —
// the caller IS the platform, not a tenant staff member).
func (q *Queries) GetTenantByIDForAdmin(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByIDForAdmin, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.SubscriptionStatus,
		&i.SubscriptionExpiresAt,
	)
	return i, err
}

const listTenantsWithStats = `-- name: ListTenantsWithStats :many
SELECT
    t.id,
    t.name,
    t.plan,
    t.created_at,
    COALESCE(branch_counts.count, 0)::int   AS branch_count,
    COALESCE(staff_counts.count, 0)::int    AS staff_count,
    COALESCE(revenue.total, 0)::float8      AS total_revenue
FROM tenants t
LEFT JOIN (
    SELECT tenant_id, COUNT(*) AS count
    FROM branches
    GROUP BY tenant_id
) branch_counts ON branch_counts.tenant_id = t.id
LEFT JOIN (
    SELECT tenant_id, COUNT(*) AS count
    FROM staff_users
    GROUP BY tenant_id
) staff_counts ON staff_counts.tenant_id = t.id
LEFT JOIN (
    SELECT tenant_id, SUM(amount) AS total
    FROM payments
    WHERE status = 'confirmed'
    GROUP BY tenant_id
) revenue ON revenue.tenant_id = t.id
ORDER BY t.created_at DESC
`

type ListTenantsWithStatsRow struct {
	ID           uuid.UUID
	Name         string
	Plan         string
	CreatedAt    time.Time
	BranchCount  int32
	StaffCount   int32
	TotalRevenue float64
}

// Per-tenant breakdown. branch_count/staff_count/total_revenue are each
// computed in their own GROUP BY subquery BEFORE joining to tenants —
// joining the raw branches/staff_users/payments tables directly here
// instead would multiply payment rows by the branch/staff fan-out and
// silently inflate total_revenue.
func (q *Queries) ListTenantsWithStats(ctx context.Context) ([]ListTenantsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listTenantsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantsWithStatsRow
	for rows.Next() {
		var i ListTenantsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plan,
			&i.CreatedAt,
			&i.BranchCount,
			&i.StaffCount,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
