// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables_sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeTableSession = `-- name: CloseTableSession :exec
UPDATE table_sessions
SET status = 'closed'
WHERE id = $1
`

func (q *Queries) CloseTableSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeTableSession, id)
	return err
}

const createTableSession = `-- name: CreateTableSession :one
INSERT INTO table_sessions (
    id,
    table_id,
    status,
    expires_at
)
VALUES ($1, $2, 'active', $3)
RETURNING id, table_id, status, expires_at, created_at
`

type CreateTableSessionParams struct {
	ID        uuid.UUID
	TableID   uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateTableSession(ctx context.Context, arg CreateTableSessionParams) (TableSession, error) {
	row := q.db.QueryRow(ctx, createTableSession, arg.ID, arg.TableID, arg.ExpiresAt)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const extendTableSession = `-- name: ExtendTableSession :exec
UPDATE table_sessions
SET expires_at = NOW() + INTERVAL '30 minutes'
WHERE id = $1
AND status = 'active'
`

func (q *Queries) ExtendTableSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, extendTableSession, id)
	return err
}

const getActiveTableSessionByTable = `-- name: GetActiveTableSessionByTable :one
SELECT id, table_id, status, expires_at, created_at
FROM table_sessions
WHERE table_id = $1
AND status = 'active'
AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveTableSessionByTable(ctx context.Context, tableID uuid.UUID) (TableSession, error) {
	row := q.db.QueryRow(ctx, getActiveTableSessionByTable, tableID)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id, table_id, status, expires_at, created_at
FROM table_sessions
WHERE status = 'active'
AND expires_at < NOW()
`

func (q *Queries) GetExpiredSessions(ctx context.Context) ([]TableSession, error) {
	rows, err := q.db.Query(ctx, getExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TableSession
	for rows.Next() {
		var i TableSession
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableSession = `-- name: GetTableSession :one
SELECT id, table_id, status, expires_at, created_at
FROM table_sessions
WHERE id = $1
`

func (q *Queries) GetTableSession(ctx context.Context, id uuid.UUID) (TableSession, error) {
	row := q.db.QueryRow(ctx, getTableSession, id)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTableSessionWithTable = `-- name: GetTableSessionWithTable :one
SELECT 
    ts.id,
    ts.table_id,
    ts.status,
    ts.expires_at,
    ts.created_at,
    t.branch_id,
    t.table_number  
FROM table_sessions ts
JOIN tables t ON t.id = ts.table_id
WHERE ts.id = $1
`

type GetTableSessionWithTableRow struct {
	ID          uuid.UUID
	TableID     uuid.UUID
	Status      string
	ExpiresAt   time.Time
	CreatedAt   time.Time
	BranchID    uuid.UUID
	TableNumber int32
}

func (q *Queries) GetTableSessionWithTable(ctx context.Context, id uuid.UUID) (GetTableSessionWithTableRow, error) {
	row := q.db.QueryRow(ctx, getTableSessionWithTable, id)
	var i GetTableSessionWithTableRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.BranchID,
		&i.TableNumber,
	)
	return i, err
}
