// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (
    id,
    branch_id,
    table_number
)
VALUES ($1,$2,$3)
RETURNING id, branch_id, table_number
`

type CreateTableParams struct {
	ID          uuid.UUID
	BranchID    uuid.UUID
	TableNumber int32
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable, arg.ID, arg.BranchID, arg.TableNumber)
	var i Table
	err := row.Scan(&i.ID, &i.BranchID, &i.TableNumber)
	return i, err
}

const getTable = `-- name: GetTable :one
SELECT id, branch_id, table_number FROM tables WHERE id = $1
`

func (q *Queries) GetTable(ctx context.Context, id uuid.UUID) (Table, error) {
	row := q.db.QueryRow(ctx, getTable, id)
	var i Table
	err := row.Scan(&i.ID, &i.BranchID, &i.TableNumber)
	return i, err
}

const getTablesByBranch = `-- name: GetTablesByBranch :many
SELECT id, branch_id, table_number
FROM tables
WHERE branch_id = $1
`

func (q *Queries) GetTablesByBranch(ctx context.Context, branchID uuid.UUID) ([]Table, error) {
	rows, err := q.db.Query(ctx, getTablesByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Table
	for rows.Next() {
		var i Table
		if err := rows.Scan(&i.ID, &i.BranchID, &i.TableNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
