// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id,
    name,
    plan
)
VALUES ($1,$2,$3)
RETURNING id, name, plan, created_at
`

type CreateTenantParams struct {
	ID   uuid.UUID
	Name string
	Plan pgtype.Text
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, plan, created_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}
